services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mailpit

  postgres:
    image: postgres:16
    container_name: cms_postgres
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: cms_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
